version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /Users/aldofusterturpin/git/By-your-side-backend/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

#  web:
#    build: .
#    environment:
#      - MONGODB_URL=mongodb://localhost:27017
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongodb